stages:
  - deploy

deploy_infra:
  stage: deploy
  image: registry.gitlab.com/babidi34/my_n8n:latest
  before_script:
    - apt update -y && apt install git ssh python3 python3-pip -y
    # Configurer SSH pour utiliser la clé privée
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_LM_INFRA" | tr -d '\r' | ssh-add -
    - echo "$SSH_PRIVATE_KEY_GITLAB" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - chmod 644 ~/.ssh/config

    - git clone -b dev_backup git@gitlab.com:linux-man/lm-infra.git
    - cd lm-infra
    - echo "$ANSIBLE_VAULT_PASSWORD_FILE" > .vault_pass.txt
    - echo "$SECRETS_INFRA_LM_FILE" > secrets-infra-lm.yml
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml
  script:
    - ansible-playbook playbooks/playbook_test.yml -i inventory.ini --vault-password-file .vault_pass.txt
  only:
    - master
