---
- hosts: all
  become: yes
  vars_files:
    - "{{ playbook_dir }}/vars_deploy_n8n.yml"
  vars:
    certbot_auto_renew_user: "www-data"
    certbot_auto_renew_options: "--quiet"
    certbot_create_if_missing: true
    nginx_custom_template: nginx-config-n8n.j2
  roles:
    - name: secure-os
    - name: geerlingguy.certbot
      when: certbot_certs is defined

#    - name: docker
#    - name: n8n-docker-compose
    - name: nginx-install
    - name: nginx
