FROM n8nio/n8n:1.30.1
USER root

RUN apk update && apk add --no-cache python3 py3-pip git openssh-client openssl
RUN openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -keyout /opt/hostname.key -out /opt/hostname.crt -subj "/C=FR/ST=France/L=Paris/O=entreprise/CN=fqdn"
RUN chmod 770 -R /opt

ENV N8N_SSL_KEY=/opt/hostname.key
ENV N8N_SSL_CERT=/opt/hostname.crt
ENV N8N_PROTOCOL=https
ENV N8N_PORT=443

ENTRYPOINT [ "n8n" ]
