---
- name: secure-os
  src: https://gitlab.com/linux-man-agences-web/ansible-role-secure-os
  scm: git
- src: https://github.com/geerlingguy/ansible-role-certbot.git
  name: geerlingguy.certbot
  scm: git
- src: https://gitlab.com/babidi34/ansible-role-n8n-docker-compose.git
  name: n8n-docker-compose
  scm: git
- src: https://gitlab.com/babidi34/ansible-role-certbot-generate.git
  name: certbot-generate
  scm: git
- src: https://gitlab.com/babidi34/ansible-role-docker.git
  name: docker
  scm: git
- src: https://github.com/nginxinc/ansible-role-nginx.git
  name: nginx-install
  scm: git
- src: https://gitlab.com/babidi34/ansible-role-nginx.git
  name: nginx
  scm: git
- src: https://gitlab.com/babidi34/ansible-role-generate-certs.git
  name: generate-certs
  scm: git